# Generated by Django 4.0.1 on 2022-01-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jurusan', models.CharField(max_length=30)),
                ('kategori', models.CharField(choices=[('SAINTEK', 'SAINTEK'), ('SOSHUM', 'SOSHUM')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=50)),
                ('kota', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Universitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_univ', models.TextField()),
                ('kota', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=15)),
                ('lName', models.CharField(max_length=15)),
                ('umur', models.IntegerField(max_length=3)),
                ('no_telepon', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asal_sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metallioApp.sekolah')),
            ],
        ),
        migrations.CreateModel(
            name='Pilihan2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metallioApp.profile')),
                ('pilihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metallioApp.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='Pilihan1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metallioApp.profile')),
                ('pilihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metallioApp.jurusan')),
            ],
        ),
        migrations.AddField(
            model_name='jurusan',
            name='univ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metallioApp.universitas'),
        ),
    ]
