# Generated by Django 4.0.1 on 2022-01-19 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metallioApp', '0002_alter_profile_umur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lName',
        ),
        migrations.AddField(
            model_name='profile',
            name='fullName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
