# Generated by Django 4.0.1 on 2022-01-19 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metallioApp', '0004_alter_profile_fullname_alter_universitas_kota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='asal_sekolah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metallioApp.sekolah'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='no_telepon',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='umur',
            field=models.IntegerField(null=True),
        ),
    ]
