# Generated by Django 4.0.1 on 2022-01-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metallioApp', '0005_alter_profile_asal_sekolah_alter_profile_no_telepon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bukti_pembayaran',
            field=models.ImageField(default='undraw_profile.svg', upload_to=''),
        ),
    ]
