# Generated by Django 4.0.1 on 2022-01-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metallioApp', '0006_profile_bukti_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pembayaran',
            field=models.CharField(choices=[('SUDAH', 'SUDAH'), ('BELUM', 'BELUM')], default='BELUM', max_length=10),
        ),
    ]
