# Generated by Django 4.0.1 on 2022-01-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metallioApp', '0007_profile_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='undraw_profile.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bukti_pembayaran',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
